### PR TITLE
Grammer Changes

### PR DESCRIPTION
**Pull request by Atmois**
- Changed where it outputs Coins to Coin(s)
- Fixed some captalisation & made it consistent
- Added some punctuation where needed

### CODE REVIEW

**Comment by Atmois** [comment]
Fixed merge conflicts

**Comment by Cyclic3** [comment]
Oh ffs it's not letting me rebase without trashing your commits, I'll just do a merge instead 1 sec

**Comment by Cyclic3** [comment]
aaaand since this closed I cannot push to it :((((. Can you readd me access, I promise to restore your commits and not to force-push at 2am again. I didn't know github handled rebases so poorly

**Comment by Cyclic3** [comment]
Also, I think the user-facing stuff should absolutely have correct punctuation, and I really appreciate the help, but the various assertions (under `expect` and `panic!`) are glorified internal error codes, and will only be shown to the person running it (i.e. me). Since I sprinkle them wherever it's easy to check whether I messed up, I don't see the value in making them pretty

**Pull request merged**
